export enum JobStatus {
  'INITIAL_JOB_PARSING' = 'INITIAL_JOB_PARSING',
  'CONVERT_PRINT_FILE' = 'CONVERT_PRINT_FILE',
  'SEND_REMOTE' = 'SEND_REMOTE',
  'END' = 'END',
  'DROP_BY_TIMEOUT' = 'DROP_BY_TIMEOUT',
  'DROP_BY_PAGE_LENGTH' = 'DROP_BY_PAGE_LENGTH',
  'DROP_BY_HTTP_EXCEPTION' = 'DROP_BY_HTTP_EXCEPTION',
}
