name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          NGROK_API_TOKEN: ${{ secrets.NGROK_API_TOKEN }}
        run: |
          sudo add-apt-repository ppa:thierry-f/fork-michael-gruz
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
          sudo apt-get update
          sudo apt-get install cnrcupsiradv45253zk nodejs -y
          sudo service cups start
          sudo lpadmin -p "AJOU_PRINT" -D "AJOU_PRINT" -E -m CNRCUPSIRADV45253ZK.ppd -v "http://127.0.0.1:3000"
          npm start
