name: CI

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          NGROK_API_TOKEN: ${{ secrets.NGROK_API_TOKEN }}
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
          sudo apt-get update
          sudo apt-get install ./drivers/cnrdrvcups-ufr2-uk_5.70-1.05_amd64.deb || sudo apt-get install ./drivers/cnrdrvcups-ufr2-uk_5.70-1.05_arm64.deb || sudo apt-get install ./drivers/cnrdrvcups-ufr2-uk_5.70-1.05_i386.deb
          sudo apt-get install nodejs -y
          sudo service cups start && sudo lpadmin -p "FILTER_PRINTER" -D "FILTER_PRINTER" -E -m CNRCUPSIRADV45253ZK.ppd -v "http://127.0.0.1:3000"
          npm start
