# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          sudo add-apt-repository ppa:thierry-f/fork-michael-gruz
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
          sudo apt-get update
          sudo apt-get install cnrcupsiradv45253zk nodejs -y
          sudo service cups start
          sudo lpadmin -p "AJOU_PRINT" -D "아주대학교 프린트" -E -m CNRCUPSIRADV45253ZK.ppd -v "http://127.0.0.1:3000"
          npm start
